[package]
name = "r12e-ir"
description = "r12e — the intermediate representation, its lifters and its interpreter."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
r12e-core = { workspace = true }
r12e-arch = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
r12e-format = { workspace = true }
r12e-analysis = { workspace = true }
r12e-arch = { workspace = true }
