#!/usr/bin/env python3
"""Generate the oracle driver from the case table.

One case table, two consumers: this driver, which runs the real machine code,
and the lifter test, which runs the same calls interpreted. Generating the
driver rather than writing it twice is what keeps the two in step.
"""

import sys
from pathlib import Path

PRELUDE = r'''
/* Generated by scripts/gen-driver.py. Do not edit. */

#include "wide.c"

const char text[] = "hello, oracle";
const char text2[] = "hello, oracls";
const u64 nums[8] = {1, 2, 3, 0x100000000ul, 5, 6, 0xfffffffffffffffful, 8};
const i32 ints[8] = {1, -2, 3, -4, 5, -6, 70000, -80000};
const i32 other[8] = {-9, 8, -7, 6, -5, 4, 30000, -20000};
const struct Point points[3] = {{1, 2, 3}, {-4, 5, -6}, {7, -8, 9}};

static u64 bits_f64(double v) {
    union {
        double d;
        u64 u;
    } x;
    x.d = v;
    return x.u;
}

static u64 bits_f32(float v) {
    union {
        float f;
        u32 u;
    } x;
    x.f = v;
    return x.u;
}

static void emit(u64 v) {
    unsigned char buf[8];
    for (int i = 0; i < 8; i++) buf[i] = (unsigned char)(v >> (i * 8));
#if defined(__x86_64__)
    register long r10 __asm__("r10");
    (void)r10;
    __asm__ volatile("syscall"
                     :
                     : "a"(1l), "D"(1l), "S"(buf), "d"(8l)
                     : "rcx", "r11", "memory");
#elif defined(__aarch64__)
    register long x8 __asm__("x8") = 64;
    register long x0 __asm__("x0") = 1;
    register const void *x1 __asm__("x1") = buf;
    register long x2 __asm__("x2") = 8;
    __asm__ volatile("svc #0" : : "r"(x8), "r"(x0), "r"(x1), "r"(x2) : "memory");
#endif
}

static void finish(void) {
#if defined(__x86_64__)
    __asm__ volatile("syscall" : : "a"(60l), "D"(0l) : "rcx", "r11");
#elif defined(__aarch64__)
    register long x8 __asm__("x8") = 93;
    register long x0 __asm__("x0") = 0;
    __asm__ volatile("svc #0" : : "r"(x8), "r"(x0));
#endif
    __builtin_unreachable();
}

void _start(void) {
'''


def argument(token: str) -> str:
    if token.startswith("&"):
        return f"(void *)&{token[1:]}"
    return token


def main() -> int:
    cases = Path(sys.argv[1])
    out = Path(sys.argv[2])
    lines = [PRELUDE]
    for raw in cases.read_text().splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        # The name carries the return kind, which the test needs and C does not.
        head = parts[0].split(":", 1)
        name = head[0]
        kind = head[1] if len(head) > 1 else "u64"
        args = ", ".join(argument(t) for t in parts[1:])
        call = f"{name}({args})"
        # A floating result is recorded as its bit pattern, because that is
        # what the register holds and what the interpreter can be compared to.
        if kind == "f64":
            lines.append(f"    emit(bits_f64({call}));\n")
        elif kind == "f32":
            lines.append(f"    emit(bits_f32({call}));\n")
        else:
            lines.append(f"    emit((u64)({call}));\n")
    lines.append("    finish();\n}\n")
    out.write_text("".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
