//! Shell completions and a man page, written from the command tree itself.
//!
//! Generated rather than checked in, because a completion script that lists
//! yesterday's subcommands is worse than none: it tells the user a command
//! exists that does not. Everything here walks clap's own tree, so adding a
//! subcommand adds it to all four outputs and nothing has to be remembered.

use std::fmt::Write as _;

use clap::Command;

/// The shells a script can be written for.
#[derive(Debug, Clone, Copy, PartialEq, Eq, clap::ValueEnum)]
pub enum Shell {
    /// GNU bash.
    Bash,
    /// Z shell.
    Zsh,
    /// fish.
    Fish,
}

/// A completion script for one shell.
pub fn completions(command: &Command, shell: Shell) -> String {
    let name = command.get_name().to_string();
    match shell {
        Shell::Bash => bash(command, &name),
        Shell::Zsh => zsh(command, &name),
        Shell::Fish => fish(command, &name),
    }
}

fn subcommands(command: &Command) -> Vec<&Command> {
    command.get_subcommands().collect()
}

/// Every option a subcommand takes, long form, including the global ones.
fn options(command: &Command, root: &Command) -> Vec<String> {
    let mut out: Vec<String> = command
        .get_arguments()
        .filter_map(|a| a.get_long().map(|l| format!("--{l}")))
        .collect();
    out.extend(
        root.get_arguments()
            .filter(|a| a.is_global_set())
            .filter_map(|a| a.get_long().map(|l| format!("--{l}"))),
    );
    out.push("--help".into());
    out.sort();
    out.dedup();
    out
}

fn bash(root: &Command, name: &str) -> String {
    let mut out = format!("# bash completion for {name}, generated by `{name} completions bash`\n");
    let names: Vec<String> = subcommands(root)
        .iter()
        .map(|c| c.get_name().to_string())
        .collect();
    let _ = writeln!(out, "_{name}() {{");
    out.push_str("    local cur prev words cword\n");
    out.push_str("    cur=\"${COMP_WORDS[COMP_CWORD]}\"\n");
    out.push_str("    local subcommand=\"\"\n");
    out.push_str("    local i\n");
    out.push_str("    for ((i = 1; i < COMP_CWORD; i++)); do\n");
    out.push_str("        case \"${COMP_WORDS[i]}\" in\n");
    let _ = writeln!(
        out,
        "            {}) subcommand=\"${{COMP_WORDS[i]}}\"; break ;;",
        names.join("|")
    );
    out.push_str("        esac\n    done\n");
    out.push_str("    case \"$subcommand\" in\n");
    for sub in subcommands(root) {
        let _ = writeln!(
            out,
            "        {}) COMPREPLY=($(compgen -W \"{}\" -- \"$cur\")); \
             [ -z \"$cur\" ] || [ \"${{cur:0:1}}\" != \"-\" ] && \
             COMPREPLY+=($(compgen -f -- \"$cur\")) ;;",
            sub.get_name(),
            options(sub, root).join(" ")
        );
    }
    let _ = writeln!(
        out,
        "        \"\") COMPREPLY=($(compgen -W \"{} --help --version\" -- \"$cur\")) ;;",
        names.join(" ")
    );
    out.push_str("    esac\n}\n");
    let _ = writeln!(out, "complete -F _{name} {name}");
    out
}

fn zsh(root: &Command, name: &str) -> String {
    let mut out = format!("#compdef {name}\n# generated by `{name} completions zsh`\n");
    let _ = writeln!(out, "_{name}() {{");
    out.push_str("    local -a commands\n    commands=(\n");
    for sub in subcommands(root) {
        let about = sub.get_about().map(|a| a.to_string()).unwrap_or_default();
        let about = about.lines().next().unwrap_or("").replace([':', '\''], " ");
        let _ = writeln!(out, "        '{}:{}'", sub.get_name(), about);
    }
    out.push_str("    )\n");
    out.push_str("    _arguments -C '1: :->command' '*:: :->argument'\n");
    out.push_str("    case $state in\n");
    let _ = writeln!(
        out,
        "        command) _describe '{name} command' commands ;;"
    );
    out.push_str("        argument)\n            case $words[1] in\n");
    for sub in subcommands(root) {
        let _ = writeln!(
            out,
            "                {}) _arguments {} '*:file:_files' ;;",
            sub.get_name(),
            options(sub, root)
                .iter()
                .map(|o| format!("'{o}'"))
                .collect::<Vec<_>>()
                .join(" ")
        );
    }
    out.push_str("            esac\n        ;;\n    esac\n}\n");
    let _ = writeln!(out, "_{name} \"$@\"");
    out
}

fn fish(root: &Command, name: &str) -> String {
    let mut out = format!("# fish completion for {name}, generated by `{name} completions fish`\n");
    let _ = writeln!(
        out,
        "complete -c {name} -f -n '__fish_use_subcommand' -a '' -d ''"
    );
    for sub in subcommands(root) {
        let about = sub.get_about().map(|a| a.to_string()).unwrap_or_default();
        let about = about.lines().next().unwrap_or("").replace('\'', " ");
        let _ = writeln!(
            out,
            "complete -c {name} -n '__fish_use_subcommand' -a '{}' -d '{about}'",
            sub.get_name()
        );
        for option in options(sub, root) {
            let _ = writeln!(
                out,
                "complete -c {name} -n '__fish_seen_subcommand_from {}' -l '{}'",
                sub.get_name(),
                option.trim_start_matches('-')
            );
        }
    }
    out
}

/// A man page in roff, section one.
pub fn manpage(root: &Command) -> String {
    let name = root.get_name().to_uppercase();
    let lower = root.get_name();
    let mut out = String::new();
    let _ = writeln!(
        out,
        ".TH {name} 1 \"\" \"{lower} {}\" \"Reverse engineering\"",
        root.get_version().unwrap_or("")
    );
    out.push_str(".SH NAME\n");
    let _ = writeln!(
        out,
        "{lower} \\- {}",
        root.get_about().map(|a| a.to_string()).unwrap_or_default()
    );
    out.push_str(".SH SYNOPSIS\n");
    let _ = writeln!(out, ".B {lower}\n[\\fICOMMAND\\fR] [\\fIOPTIONS\\fR]");

    if let Some(long) = root.get_long_about() {
        out.push_str(".SH DESCRIPTION\n");
        for line in long.to_string().lines() {
            if line.trim().is_empty() {
                out.push_str(".PP\n");
            } else {
                let _ = writeln!(out, "{}", escape(line));
            }
        }
    }

    out.push_str(".SH COMMANDS\n");
    for sub in subcommands(root) {
        let _ = writeln!(out, ".TP\n.B {}", sub.get_name());
        let about = sub
            .get_long_about()
            .or_else(|| sub.get_about())
            .map(|a| a.to_string())
            .unwrap_or_default();
        for line in about.lines() {
            if line.trim().is_empty() {
                out.push_str(".PP\n");
            } else {
                let _ = writeln!(out, "{}", escape(line));
            }
        }
        let taken = options(sub, root);
        if taken.len() > 1 {
            let _ = writeln!(out, ".RS\n.PP\nOptions: {}\n.RE", taken.join(", "));
        }
    }

    out.push_str(".SH EXIT STATUS\n");
    out.push_str(".TP\n.B 0\nThe command did what was asked.\n");
    out.push_str(".TP\n.B 1\nWhat was asked for was not found.\n");
    out.push_str(".TP\n.B 2\nThe command line was wrong.\n");
    out.push_str(".TP\n.B 3\nThe input could not be read.\n");
    out
}

/// Roff takes a leading dot as a request, and a backslash as an escape.
fn escape(line: &str) -> String {
    let line = line.replace('\\', "\\\\");
    if line.starts_with('.') || line.starts_with('\'') {
        format!("\\&{line}")
    } else {
        line
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::CommandFactory;

    fn command() -> Command {
        crate::Cli::command()
    }

    #[test]
    fn every_subcommand_appears_in_every_shell() {
        let root = command();
        let names: Vec<String> = root
            .get_subcommands()
            .map(|c| c.get_name().to_string())
            .collect();
        assert!(names.len() > 5, "only {} subcommands", names.len());
        for shell in [Shell::Bash, Shell::Zsh, Shell::Fish] {
            let script = completions(&command(), shell);
            for name in &names {
                assert!(
                    script.contains(name.as_str()),
                    "{shell:?} completion does not mention {name}"
                );
            }
        }
    }

    #[test]
    fn the_man_page_names_every_command() {
        let page = manpage(&command());
        for sub in command().get_subcommands() {
            assert!(
                page.contains(sub.get_name()),
                "the man page does not mention {}",
                sub.get_name()
            );
        }
        assert!(page.starts_with(".TH E5R 1"));
    }

    #[test]
    fn a_roff_request_in_the_text_is_escaped() {
        // A line starting with a dot would be a formatting request.
        assert_eq!(escape(".notarequest"), "\\&.notarequest");
        assert_eq!(escape("ordinary"), "ordinary");
    }
}
